big_icon_size 256
small_icon_size 96
banner icons/256-96/bg_dark.png
font fonts/source-code-pro-extralight-32.png
icons_dir icons/256-96
selection_big icons/256-96/selection_dark-big.png
selection_small icons/256-96/selection_dark-small.png
